# Generated by Django 5.0.1 on 2024-03-19 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_brand_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCat',
            fields=[
                ('pro_cat_name', models.CharField(max_length=100, primary_key=100, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('mobile', models.PositiveBigIntegerField(unique=True)),
                ('dis_pic', models.ImageField(upload_to='')),
                ('address', models.TextField()),
                ('address_pin', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('pan_id', models.CharField(max_length=100, unique=True)),
                ('pan_pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_img', models.ImageField(upload_to='')),
                ('pro_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pro_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('pro_dis', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pro_brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productbrand')),
            ],
        ),
        migrations.AddField(
            model_name='productbrand',
            name='pro_cat_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productcat'),
        ),
    ]
